- examples/example.typ
- lib.typ
- slide.typ
This is the `touying-reducer` function that Touying is planning to add. It allows decoupling Touying from specific packages dependencies, while still enabling easy support for `pause` and `meanwhile` animations for Cetz and Fletcher. Any suggestions on Touying's interface are welcome :-) @johannes-wolf @Jollywatt @fenjalien 
```typst
#import "../lib.typ": *
#import "@preview/cetz:0.2.0"
#import "@preview/fletcher:0.4.1" as fletcher: node, edge
#let cetz-canvas = touying-reducer.with(reduce: cetz.canvas, cover: cetz.draw.hide)
#let fletcher-diagram = touying-reducer.with(reduce: (arr, ..args) => fletcher.diagram(..args, ..arr))
#let s = themes.metropolis.register(s, aspect-ratio: "16-9", footer: self => self.info.institution)
#let (init, slide) = utils.methods(s)
#show: init
// cetz …
```
> feat: add touying-reducer for cetz and fletcher animation

- examples/aqua-zh.typ
- examples/aqua.typ
- examples/dewdrop.typ
- examples/example.typ
- examples/metropolis.typ
- examples/simple.typ
- examples/slides.typ
- examples/university.typ
- lib.typ
- themes/aqua.typ
- themes/default.typ
- themes/dewdrop.typ
- themes/metropolis.typ
- themes/simple.typ
- themes/themes.typ
- themes/university.typ
Don't export variable `s` by default anymore.
1. make `self` parameter in `register` a named parameter instead of positional parameter, and change syntax `#let s = themes.university.register(s, aspect-ratio: "16-9")` to `#let s = themes.university.register(aspect-ratio: "16-9")`.
2. add `default` theme to export a empty/default `s`, like `#let s = themes.default.register(aspect-ratio: "16-9")`
Alternative to #14
> refactor: don't export variable `s` by default anymore

- slide.typ
- utils/utils.typ
Implement #21.
we can access `subslide` and `repeat` in footer by code like `footer: self => self.subslide` and `footer: self => self.repeat`.
> feat: access subslide and repeat in footer and header

- slide.typ
- themes/aqua.typ
- themes/dewdrop.typ
- themes/metropolis.typ
- themes/simple.typ
- themes/university.typ
- utils/utils.typ
(Original page layout ↑)
To support footnote, we need to modify the page layout of the slide from:
```typst
page(
header: header,
pad(
body
),
footer: footer,
)
```
to
```
set page(
header: negative-pad(header),
footer: negative-pad(footer),
)
body
```
structure.
Where `let negative-pad = pad.with(x: -margin.x)`, which extends the header/footer to occupy the entire width of the page.
As a result, we remove the `self.padding` parameter and add `self.full-header` and `self.full-footer` to control whether this feature is enabled (not enabled for the simple theme, but enabled for all other themes).
This PR is a breaking change, but it enables support for footnote #26 and allows normal usage of `set align(horizon)` set rule.
cc @sefidel and @fran-miao
> refactor: remove `padding` and add `full-header`, `full-footer` to support footnote

- slide.typ
- utils/states.typ
fixed #23.
However, we will not be able to create two adjacent and identical sections.
> feat: add `self.duplicate = false` to remove duplicate sections

- README.md
- docs/docs/external/pympress.md
- docs/docs/external/typst-preview.md
- docs/docs/start.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/external/pympress.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/external/typst-preview.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/start.md
- docs/i18n/zh/docusaurus-plugin-content-docs/version-0.3.2+/start.md
- docs/i18n/zh/docusaurus-plugin-content-docs/version-0.3.x/start.md
- docs/i18n/zh/docusaurus-plugin-content-docs/version-0.4.0+/start.md
- docs/versioned_docs/version-0.3.2+/start.md
- docs/versioned_docs/version-0.3.x/start.md
- docs/versioned_docs/version-0.4.0+/start.md
- examples/example.typ
- slide.typ
- themes/aqua.typ
- themes/metropolis.typ
- themes/university.typ
- utils/pdfpc.typ
- utils/states.typ
```typst
#let s = (s.methods.show-notes-on-second-screen)(self: s, right)
#speaker-note[
+ This is a speaker note.
+ You won't see it unless you use `#let s = (s.math.show-notes-on-second-screen)(self: s, right)`
]
```
Add speaker note support for dual screens. It is compatible with beamer, so we can use [dspdfviewer](https://dspdfviewer.danny-edel.de/) or [pympress](https://github.com/Cimbali/pympress) for presentation with speaker notes. I personally recommend pympress because of its feature-rich and simple installation.
https://github.com/touying-typ/touying/blob/dc0910b5af6fb12f8cd4d746bb672373d60b65a9/examples/example.typ#L85-L88
[example.pdf](https://github.com/touying-typ/touying/files/15283621/example.pdf)
cc @cooki35 @zouharvi @JuliusFreudenberger, maybe @laurmaedje for …
> feat: add speaker note support for dual screens

- slide.typ
- themes/aqua.typ
- themes/dewdrop.typ
- themes/metropolis.typ
- themes/simple.typ
- themes/university.typ
- utils/pdfpc.typ
- utils/states.typ
- utils/utils.typ
This PR updates touying to typst 11, removing calls to `style` and `locate` and thereby removing deprecation warnings.
> Update to typst 11

- src/core.typ
Fixes #73
```typst
#import "lib.typ": themes
#import themes.simple: simple-theme
#show: simple-theme.with(aspect-ratio: "16-9")
#square()
```
> fix: Allow a `content` to have no `body`

- src/core.typ
Solve https://github.com/touying-typ/touying/issues/77
Previous, the items in cells will be omitted due to `continue`.
I am not quite familiar with the code. If it has conflicts with other exist functions, maybe we could add a `if` instead? 
Like
```
if kind !="touying-fn-wrapper" {
continue
}
```
> fix: fix no alert in table cells 

- src/core.typ
- src/utils.typ
`alternatives` uses the measure function to measure the width and height of all contents, which leads to an issue where the width and height are 0 when using context expressions, so that the content is not displayed.
We've added a `stretch` argument to alternatives and its friends. When `#alternatives(stretch: false)[A][B]` is set, the width and height will not be measured, and the original content will be displayed directly. So you can use the codly package normally.
Also, there was a bug in the original mark-style alternatives implementation, which has now been fixed.
@road21
> fix: fix mark-style alternatives and add stretch argument to fix #91

- src/components.typ
- themes/dewdrop.typ
I was rather disappointed when, trying to disable linebreaks in the minipages of the `dewdrop` theme, the option for it did not seem to function as described:
>  -  `display-subsection` is whether we add linebreak between subsections.
In actuality, this option (as the doc for `mini-slides` describes) just enables/disables circles for subsection slides.
In this PR, I fixed the documentation and implemented the `linebreaks` feature that adds the behaviour I was looking for:
| `linebreaks: true` | `linebreaks: false` |
|------------------|------------------|
| ![image](https://github.com/user-attachments/assets/9be696e5-e800-4fc7-b182-ac1e05a492b9) |![image](https://github.com/user-attachments/assets/e461b232-7bf4-4725-9d8a-f38808788b4f) |
> feat: add `linebreaks` option to components.mini-slides

- src/components.typ
I found an issue with the rendering of progress bars in the section slides. I have added a single line of code to prevent this problem.
Thank you for considering my contribution. Feel free to use or modify it as needed!
```typst
#import "@preview/touying:0.5.3": *
#import themes.metropolis: *
#show: metropolis-theme
#set grid(gutter: 1em)
= First chapter
= Second chapter
```
This is how the example above renders in typst.app.
You may see the progress bar is broken in the first chapter title slide.
> fix progress bar not to break apart

- src/core.typ
- src/utils.typ
This PR addresses a bug in the frozen-counters functionality where status updates show unexpected behavior when using multiple `#pause` commands. This issue may be related to #72.
When using multiple `#pause` commands, figure captions are not correctly incremented. For example, in the example below with multiple figures and pauses, the final figure might be captioned as "Figure 2:" though it should be "Figure 3:".
```typst
#import "@preview/touying:0.5.3": *
#import themes.simple: *
#show: simple-theme
== slide 1
#figure([test figure], caption: [caption])
== slide 2
#figure([test figure], caption: [caption])
#pause
paused
== slide 3
#figure([test figure], caption: [caption])
#pause
paused
```
Instead of storing the counter value at the beginning of a sequence of subslides, we now store …
> Fix frozen-counters bug with multiple #pause commands

- src/core.typ
I removed one line to correctly handle page numbering when draft mode is true. This change resolves issue #121.
I've tested it to ensure pagination works as expected in draft mode with the example given in #121.
Ready for review!
> fix: incorrect page num when draft is true

- themes/metropolis.typ
I discovered a bug in the metropolis theme where the header was returning the function itself instead of calling it. This causes an error when trying to specify the slide title.
```typst
#import "@preview/touying:0.5.3": *
#import themes.metropolis: *
#show: metropolis-theme
#slide(title: "section with a title")[
error!
]
```
> fix: metropolis slide's header to return content if title is specified

- src/utils.typ
This PR addresses the behaviors of the `fit-to-height` and `fit-to-width` functions, resolving issues related to #109.
1. **Changed to use the `width` and `height` parameters of `measure`:** Replaced previous hacks using hidden labels with `measure`'s width and height parameters to accurately determine relative sizes within a container.
2. **Removed nested box for `scale`:** Eliminated the need for a nested box to handle the size of the `scale` by utilizing the `reflow` parameter of `scale`.
3. **Updated examples in the comment:** The actual size of `1fr` is determined by other `fr`s in the same container, so only one `0.5fr` in the container is equivalent to `100%`. To avoid this confusion, I slightly changed the documented examples to use `%` instead.
- In simple theme, the headings are …
> fix: behaviors of `fit-to-height` and `fit-to-width`

- src/core.typ
Instead of using `place` and `hide` to handle headings, we can use `show heading: none`. I borrowed this idea from another slide maker library, Slydst. Using this approach, we can avoid placing the entity of headings, thus resolving #110.
I have tested this with the examples in the directory.
Please review.
By the way, thank you for creating this wonderful library. I'm now completely obsessed with thinking about how I can contribute to making it even better!
> fix: duplicated footnotes in headings

- themes/metropolis.typ
Let `new-section-slide` of Metropolis theme respect `self.colors` to fix [this bug](https://forum.typst.app/t/touying-metropolis-theme-what-is-the-variable-to-define-the-color-of-titles-in-section-slides/1992/1).
> fix: respect colors dict in metropolis theme

- src/utils.typ
This pull request introduces a new (pseudo) semitransparent cover function that provides a method for hiding content in slides. The function changes the text color of elements to a specified color if they contain text. If an element does not contain text, it can use `hide` as a fallback.
This implementation has been successfully tested with the default examples and the specific example provided in issue #112.
> feat: add cover color-changing-cover

- src/core.typ
Hello,
I had a use-case for a different page size (i.e. higher dpi). However, manually providing width and height to the page broke the speaker notes feature. Just replacing the hard-coded values with the actual page size seems to just work fine.
> fix: do not hardcode page sizes

- src/core.typ
- src/utils.typ
See https://github.com/touying-typ/touying/issues/111. Could we reuse the definition of `effect` from utils.typ in core.typ? Right now, `effect` from utils.typ doesn't get an argument `is-method`.
> Reuse effect from utils

- src/utils.typ
Currently, `color-changing-cover` and `alpha-changing-cover` cannot override the colors of equations correctly.
I found that we can use the regex `.+` to match every string and override the colors of equations.
Thanks.
Closes #156
> fix: use regex to override colors of equations

- src/components.typ
`sym.circle` creates a big, hollow circle whereas `sym.circle.fill` creates a small, filled circle.  Replaced `sym.circle` with `sym.circle.small` to have consistent circle size.
> fix: use correct circle symbol
